[[vtkfig]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "745e0486d0a9ed22231cafbc7880ab4047f87fce"
libc = "glibc"
os = "linux"

    [[vtkfig.download]]
    sha256 = "e77382cb9807235505c43f4d48b0eac32b3c9f094e22201409f041c996e553ac"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.0+0/vtkfig.v0.25.0.aarch64-linux-gnu-cxx11.tar.gz"
[[vtkfig]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b53617990a512d1a02a79d71992380b63cfe3685"
libc = "glibc"
os = "linux"

    [[vtkfig.download]]
    sha256 = "56c938e6c5463217c738f792b04d2ee8385871c1954d0277347df35a24c9a92a"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.0+0/vtkfig.v0.25.0.i686-linux-gnu-cxx11.tar.gz"
[[vtkfig]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9991697354cb07da6def92fcc5bae3d36a21bc4"
libc = "musl"
os = "linux"

    [[vtkfig.download]]
    sha256 = "8e990c961abf49f5dad9ba62e56021707c1c044b4db9f16541b4e7e287c6a280"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.0+0/vtkfig.v0.25.0.aarch64-linux-musl-cxx11.tar.gz"
[[vtkfig]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1d7fb922dc9e8260e796cfd3ca83111e5f866a4"
libc = "musl"
os = "linux"

    [[vtkfig.download]]
    sha256 = "7a8214e2d1e658baad56993185d20d24fe3b800562d7ab7b8932a71a3092f6a1"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.0+0/vtkfig.v0.25.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[vtkfig]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4308aeba501da732f16a5854c386271e27ab3217"
libc = "musl"
os = "linux"

    [[vtkfig.download]]
    sha256 = "bb4f34fdc283a67dd25dd3e48ff25bff5288df097fb5917cbed4062b4cc925b0"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.0+0/vtkfig.v0.25.0.i686-linux-musl-cxx11.tar.gz"
[[vtkfig]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efe52288893869e497e897e58b1d63c56637a10c"
libc = "musl"
os = "linux"

    [[vtkfig.download]]
    sha256 = "974a8d89e1d5f7fc928089771933f79ff53903cfaaa879bd97aa243cdd893ff7"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.0+0/vtkfig.v0.25.0.x86_64-linux-musl-cxx11.tar.gz"
[[vtkfig]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0eec72cdf8f8d7e5338763bf47c0c75d9a9d5324"
libc = "glibc"
os = "linux"

    [[vtkfig.download]]
    sha256 = "f251c32b644227cbf208987b13e201c160e44c38011b0648c2cd5e905c5694b7"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.0+0/vtkfig.v0.25.0.x86_64-linux-gnu-cxx11.tar.gz"
[[vtkfig]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c7ca2d178c4fa2e452657ba241f5c144e369f0f"
libc = "glibc"
os = "linux"

    [[vtkfig.download]]
    sha256 = "081f216864cfd1356d004b738ae5c42937a056f96304c00f6f7cb12197ce29dc"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.0+0/vtkfig.v0.25.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[vtkfig]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29b361f6fab2308efa8b8c761e43e5ebe052064b"
libc = "glibc"
os = "linux"

    [[vtkfig.download]]
    sha256 = "e76beab96fceb69d023e5e812090af7e6c8feb1a08c2f3f4076151bbd816ecb6"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.0+0/vtkfig.v0.25.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[vtkfig]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f88d5fa6bb1709c065de8b04eeed75fe71140598"
os = "freebsd"

    [[vtkfig.download]]
    sha256 = "4c4602daae9fb611fce6b574cf5f46ea7f49727636de8f6f1f18597c00d3a64d"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.0+0/vtkfig.v0.25.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
