[[vtkfig]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ed293678cdbe3184baaafb75a7ce0d750233f1d"
libc = "glibc"
os = "linux"

    [[vtkfig.download]]
    sha256 = "eb678029ad0e822c63e90d4d4f6794820df405f9b9144b86687889da266186e7"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.24.4+0/vtkfig.v0.24.4.aarch64-linux-gnu-cxx11.tar.gz"
[[vtkfig]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae7782ef2c8c8dd075ed523c1a77ad2d3d96b448"
libc = "glibc"
os = "linux"

    [[vtkfig.download]]
    sha256 = "b373cc220db4162c7223275abefc4720ffc43e016e1136a1a51ee6012d822cbd"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.24.4+0/vtkfig.v0.24.4.i686-linux-gnu-cxx11.tar.gz"
[[vtkfig]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d2e2577b0f6fa676cf9771addb29418e34ab8b8"
libc = "musl"
os = "linux"

    [[vtkfig.download]]
    sha256 = "00a7941988d658512645f139493985f3ccd2b05ac59c86cbb13eb2c4b91a606a"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.24.4+0/vtkfig.v0.24.4.aarch64-linux-musl-cxx11.tar.gz"
[[vtkfig]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4bdad839fa62bd1ad6eebc64b01a739896bff7d"
libc = "musl"
os = "linux"

    [[vtkfig.download]]
    sha256 = "420fab67765497a2cd8f112db945e1391e735fda70000b8877086b4ec246624d"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.24.4+0/vtkfig.v0.24.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[vtkfig]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83497e6773d07d010582c5736e619a5d72de7f9b"
libc = "musl"
os = "linux"

    [[vtkfig.download]]
    sha256 = "2c112a06962652516726e3a73ed01ef9284af5246fbc3389ac22f76ffd888458"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.24.4+0/vtkfig.v0.24.4.i686-linux-musl-cxx11.tar.gz"
[[vtkfig]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34b33fc91288b700a4358b92f983a41c1352be60"
libc = "musl"
os = "linux"

    [[vtkfig.download]]
    sha256 = "56f4b0d9d8816281f63b3da3b1165d2fd10345a48db8d2aaaa99beb71a28fd54"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.24.4+0/vtkfig.v0.24.4.x86_64-linux-musl-cxx11.tar.gz"
[[vtkfig]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e079876a15f732d05626e7e3e6f7d8455a70d41"
libc = "glibc"
os = "linux"

    [[vtkfig.download]]
    sha256 = "2b9f7e0506d5c3258fdb085825adf7e138d267512ca98801ba1592c939aec619"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.24.4+0/vtkfig.v0.24.4.x86_64-linux-gnu-cxx11.tar.gz"
[[vtkfig]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc8349bb581a73ece3b475b4f2aaffa47af2fd7a"
libc = "glibc"
os = "linux"

    [[vtkfig.download]]
    sha256 = "9cc9657fb965df448815b2a5cbb41a83fecccc60ba3eacfb1d6282afbd89d449"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.24.4+0/vtkfig.v0.24.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[vtkfig]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12a5df58824efd72a2b6d53f2af405b65e2219d0"
libc = "glibc"
os = "linux"

    [[vtkfig.download]]
    sha256 = "94f73ee0e03d883b5eefeadb869f719b8cc34c66c14c06b1146dda4176c3e8b1"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.24.4+0/vtkfig.v0.24.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[vtkfig]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df0870e4b2834f610ef97793edf9e462f6813361"
os = "freebsd"

    [[vtkfig.download]]
    sha256 = "0fa1e54eaa35d7da2549158f4d4d5566eb6b8752c277f488af3f164a23ffa731"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.24.4+0/vtkfig.v0.24.4.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
