[[vtkfig]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8ea63d514f4ed782abe71fd25c4afb2ff498ae5"
libc = "glibc"
os = "linux"

    [[vtkfig.download]]
    sha256 = "ec97b8143fc623ed19acf063bd8bca01506a3a2d1ac2f85ebecfd9cec261a192"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.1+0/vtkfig.v0.25.1.aarch64-linux-gnu-cxx11.tar.gz"
[[vtkfig]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "265c3efc412025874ea65779518c689f4cf11157"
libc = "glibc"
os = "linux"

    [[vtkfig.download]]
    sha256 = "34364e3159e83d3e9a29666bce427186e2e0985f2b07fb9137e938eac797e22a"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.1+0/vtkfig.v0.25.1.i686-linux-gnu-cxx11.tar.gz"
[[vtkfig]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "938beb1f973b4d42f70196995796372758a7842a"
libc = "musl"
os = "linux"

    [[vtkfig.download]]
    sha256 = "f5340a14900cbfd02d17357c38768aa3073358a4e2b596109411be84a513f694"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.1+0/vtkfig.v0.25.1.aarch64-linux-musl-cxx11.tar.gz"
[[vtkfig]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7039b54805c41e6f636ff232dd8bee2e403c115"
libc = "musl"
os = "linux"

    [[vtkfig.download]]
    sha256 = "d34150a605cebee95706c771be411b42b70e724b888a6ed53e7eee7269ced76c"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.1+0/vtkfig.v0.25.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[vtkfig]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cf3f30db2ab1270d8a54854983e0ea5357d02fce"
libc = "musl"
os = "linux"

    [[vtkfig.download]]
    sha256 = "a6371d117aa015917ada5d644383dded6ab36dbdd8b5726c2a9315e6076c63bf"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.1+0/vtkfig.v0.25.1.i686-linux-musl-cxx11.tar.gz"
[[vtkfig]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec9e495e56ae5e2eadc782cbb7b102e9a1f9e86b"
libc = "musl"
os = "linux"

    [[vtkfig.download]]
    sha256 = "4d12c4f04d8fb0cb02146a23d6a4e228328009ecb6452a936978a64c3ad8eaf2"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.1+0/vtkfig.v0.25.1.x86_64-linux-musl-cxx11.tar.gz"
[[vtkfig]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "486d1ed43cb9ff00759ea50a8123e11ef3c35de6"
libc = "glibc"
os = "linux"

    [[vtkfig.download]]
    sha256 = "5a143325893cc65403bdf892079a19204d69ff4f2c81992c7f3b80620a8cc9cf"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.1+0/vtkfig.v0.25.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[vtkfig]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbdbb108a7f5fce5e28c52718f7f0b9b3bf51d0a"
libc = "glibc"
os = "linux"

    [[vtkfig.download]]
    sha256 = "8cdc3049a57da7b01a0871927a2a1a3a8dc9509d08ae3013cd807f404c05d065"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.1+0/vtkfig.v0.25.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[vtkfig]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3603201a9860a1f4737ab8e6d1fa253bcbacd956"
os = "freebsd"

    [[vtkfig.download]]
    sha256 = "7ced4774e7215e5ef530cf251d7edfedc54450edef425a5c1819537d771e758f"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.1+0/vtkfig.v0.25.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[vtkfig]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ece094ce47e5eb95f8b83071e12551018e815a2"
libc = "glibc"
os = "linux"

    [[vtkfig.download]]
    sha256 = "668e6248a2963feb72ec920689289564ebc352a06f760388604fa874467a8310"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.25.2+0/vtkfig.v0.25.2.x86_64-linux-gnu-cxx11.tar.gz"
