[[vtkfig]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b191de39934b0b3c700b07b7c5a54919bdecea0"
libc = "glibc"
os = "linux"

    [[vtkfig.download]]
    sha256 = "e1dae83690522825f1c30f8ef6049fcce12480b7c683f9b0aaa0c122d281359c"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.24.1+0/vtkfig.v0.24.1.x86_64-linux-gnu-cxx11.tar.gz"
