[[vtkfig]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1465c16a58c5211fec4a579b74a577e9c3b11aa"
libc = "glibc"
os = "linux"

    [[vtkfig.download]]
    sha256 = "33d2cf57a90a305d5ec8ed9d2f14dd752c2811be078bd56fa396fc05ad20dba7"
    url = "https://github.com/j-fu/vtkfig_jll.jl/releases/download/vtkfig-v0.22.0+0/vtkfig.v0.22.0.x86_64-linux-gnu-cxx11.tar.gz"
